{% set name = "stream-inflate" %}
{% set version = "0.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1959c5f01d920dd68065795f51eb4d177eb5a1216a3b08cf9d2e07b93f73cc5b

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - cython >=3.0.0
  run:
    - python

test:
  imports:
    - stream_inflate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/michalc/stream-inflate
  summary: Uncompress DEFLATE streams in pure Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
