{% set name = "stream-inflate" %}
{% set version = "0.0.40" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0f5458273cf5e82b01d50f170c59f6b976e6c86c54d0aee2808c3c8b634982de

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - cython >=3.0.0
  run:
    - python

test:
  imports:
    - stream_inflate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/michalc/stream-inflate
  summary: Uncompress DEFLATE streams in pure Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
