{% set name = "stream-inflate" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 28e610daf4ca13ad8e65c20f6eb49d09d372d34b3f13ab5fbec553b871c176ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6.7,!=3.7.0
    - hatchling
  run:
    - python >=3.6.7,!=3.7.0

test:
  imports:
    - stream_inflate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/michalc/stream-inflate
  summary: Uncompress DEFLATE streams in pure Python
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
